name: frost
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  english_words: ^3.1.0
  cupertino_icons: ^0.1.2
  firebase_auth:
#  carousel_slider: ^1.3.0
  cloud_firestore: ^0.12.9+4
  loading: ^1.0.1
#  uuid: 2.0.1
  font_awesome_flutter: ^8.5.0
#  charts_flutter: ^0.8.1
  fluttertoast: ^3.1.3
#  flutter_icons: ^0.3.1
  provider: ^3.1.0+1
#  get_it: ^3.0.3

#  loading_animations: "^2.0.0"
#  eva_icons_flutter: ^2.0.0
#  url_launcher: ^5.1.2

  flutter_launcher_icons: "^0.7.3"
  avatar_glow:

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launch.png"

flutter:
  uses-material-design: true
  assets:

    - images/aec.png
    - assets/images/logo.png
    - assets/images/mountains.jpg
    - assets/images/launch1.png
    - assets/images/aec.jpg
    - assets/images/1.png
    - assets/images/assam.png

